insert into category (name) values ('dapibus');
insert into category (name) values ('non');
insert into category (name) values ('sagittis');
insert into category (name) values ('odio');
insert into category (name) values ('rutrum');
insert into category (name) values ('donec');
insert into category (name) values ('platea');
insert into category (name) values ('bibendum');
insert into category (name) values ('scelerisque');
insert into category (name) values ('tincidunt');
insert into category (name) values ('morbi');

=========================================================

insert into category (name, id_category_1) values ('justo sollicitudin', 6);
insert into category (name, id_category_1) values ('phasellus id', 8);
insert into category (name, id_category_1) values ('iaculis', 6);
insert into category (name, id_category_1) values ('rutrum nulla', 4);
insert into category (name, id_category_1) values ('in hac', 10);
insert into category (name, id_category_1) values ('donec', 6);
insert into category (name, id_category_1) values ('a', 10);
insert into category (name, id_category_1) values ('in libero', 9);
insert into category (name, id_category_1) values ('nam', 1);
insert into category (name, id_category_1) values ('in lacus', 7);
insert into category (name, id_category_1) values ('rutrum', 11);
insert into category (name, id_category_1) values ('non', 2);
insert into category (name, id_category_1) values ('suspendisse potenti', 11);
insert into category (name, id_category_1) values ('nulla sed', 5);
insert into category (name, id_category_1) values ('quisque', 4);
insert into category (name, id_category_1) values ('mattis nibh', 7);
insert into category (name, id_category_1) values ('nam ultrices', 4);
insert into category (name, id_category_1) values ('lorem', 10);
insert into category (name, id_category_1) values ('imperdiet', 2);
insert into category (name, id_category_1) values ('augue aliquam', 5);
insert into category (name, id_category_1) values ('volutpat eleifend', 9);
insert into category (name, id_category_1) values ('tempor turpis', 7);
insert into category (name, id_category_1) values ('donec', 10);
insert into category (name, id_category_1) values ('suspendisse potenti', 1);
insert into category (name, id_category_1) values ('cubilia', 10);
insert into category (name, id_category_1) values ('luctus et', 2);
insert into category (name, id_category_1) values ('nunc rhoncus', 9);
insert into category (name, id_category_1) values ('nullam', 7);
insert into category (name, id_category_1) values ('orci pede', 4);
insert into category (name, id_category_1) values ('purus', 9);
insert into category (name, id_category_1) values ('ultrices', 11);
insert into category (name, id_category_1) values ('nulla', 4);
insert into category (name, id_category_1) values ('pede justo', 11);
insert into category (name, id_category_1) values ('vel', 10);
insert into category (name, id_category_1) values ('praesent', 2);
insert into category (name, id_category_1) values ('sit amet', 3);
insert into category (name, id_category_1) values ('pretium iaculis', 4);
insert into category (name, id_category_1) values ('ligula sit', 9);
insert into category (name, id_category_1) values ('enim leo', 11);
insert into category (name, id_category_1) values ('tincidunt ante', 2);
insert into category (name, id_category_1) values ('nec', 5);
insert into category (name, id_category_1) values ('vestibulum', 4);
insert into category (name, id_category_1) values ('magna vestibulum', 11);
insert into category (name, id_category_1) values ('nec', 2);
insert into category (name, id_category_1) values ('eros', 7);
insert into category (name, id_category_1) values ('non', 1);
insert into category (name, id_category_1) values ('eu interdum', 4);
insert into category (name, id_category_1) values ('cubilia curae', 10);
insert into category (name, id_category_1) values ('odio', 11);
insert into category (name, id_category_1) values ('ipsum primis', 5);
insert into category (name, id_category_1) values ('ultrices', 7);
insert into category (name, id_category_1) values ('curae', 8);
insert into category (name, id_category_1) values ('ligula', 11);
insert into category (name, id_category_1) values ('aenean', 8);
insert into category (name, id_category_1) values ('ligula suspendisse', 11);
insert into category (name, id_category_1) values ('leo', 8);
insert into category (name, id_category_1) values ('dapibus', 2);
insert into category (name, id_category_1) values ('aenean', 3);