insert into category (name, id_category_1) values ('justo sollicitudinis', 6);
insert into category (name, id_category_1) values ('phasellus idis', 8);
insert into category (name, id_category_1) values ('iaculisis', 6);
insert into category (name, id_category_1) values ('rutrum nullais', 4);
insert into category (name, id_category_1) values ('in hacis', 10);
insert into category (name, id_category_1) values ('donecisi', 6);
insert into category (name, id_category_1) values ('ais', 10);
insert into category (name, id_category_1) values ('in liberois', 9);
insert into category (name, id_category_1) values ('namis', 1);
insert into category (name, id_category_1) values ('in lacusis', 7);
insert into category (name, id_category_1) values ('rutrumis', 11);
insert into category (name, id_category_1) values ('nonis', 2);
insert into category (name, id_category_1) values ('suspendisse potentiisi', 11);
insert into category (name, id_category_1) values ('nulla sedis', 5);
insert into category (name, id_category_1) values ('quisqueis', 4);
insert into category (name, id_category_1) values ('mattis nibhis', 7);
insert into category (name, id_category_1) values ('nam ultricesis', 4);
insert into category (name, id_category_1) values ('loremis', 10);
insert into category (name, id_category_1) values ('imperdietis', 2);
insert into category (name, id_category_1) values ('augue aliquamis', 5);
insert into category (name, id_category_1) values ('volutpat eleifendis', 9);
insert into category (name, id_category_1) values ('tempor turpisis', 7);
insert into category (name, id_category_1) values ('donecis', 10);
insert into category (name, id_category_1) values ('suspendisse potentiis', 1);
insert into category (name, id_category_1) values ('cubiliais', 10);
insert into category (name, id_category_1) values ('luctus etis', 2);
insert into category (name, id_category_1) values ('nunc rhoncusis', 9);
insert into category (name, id_category_1) values ('nullamis', 7);
insert into category (name, id_category_1) values ('orci pedeis', 4);
insert into category (name, id_category_1) values ('purusis', 9);
insert into category (name, id_category_1) values ('ultrice sis', 11);
insert into category (name, id_category_1) values ('nuellais', 4);
insert into category (name, id_category_1) values ('pede justois', 11);
insert into category (name, id_category_1) values ('velis', 10);
insert into category (name, id_category_1) values ('praesentis', 2);
insert into category (name, id_category_1) values ('sit ametis', 3);
insert into category (name, id_category_1) values ('pretium iaculisis', 4);
insert into category (name, id_category_1) values ('ligurla sitis', 9);
insert into category (name, id_category_1) values ('enim leois', 11);
insert into category (name, id_category_1) values ('tincidunt anteis', 2);
insert into category (name, id_category_1) values ('ne cis', 5);
insert into category (name, id_category_1) values ('vestibulumis', 4);
insert into category (name, id_category_1) values ('magna vestibulumis', 11);
insert into category (name, id_category_1) values ('necis', 2);
insert into category (name, id_category_1) values ('erosis', 7);
insert into category (name, id_category_1) values ('noniis', 1);
insert into category (name, id_category_1) values ('eu interdumis', 4);
insert into category (name, id_category_1) values ('cubilia curaeis', 10);
insert into category (name, id_category_1) values ('odiois', 11);
insert into category (name, id_category_1) values ('ipsum primisis', 5);
insert into category (name, id_category_1) values ('ultricesios', 7);
insert into category (name, id_category_1) values ('curaeis', 8);
insert into category (name, id_category_1) values ('ligulais', 11);
insert into category (name, id_category_1) values ('aeneaniso', 8);
insert into category (name, id_category_1) values ('ligula suspendisseis', 11);
insert into category (name, id_category_1) values ('leois', 8);
insert into category (name, id_category_1) values ('dapibusis', 2);
insert into category (name, id_category_1) values ('aeneanis', 3);